python reset_results.py 
python pacman.py -l capsuleClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l capsuleClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l capsuleClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l contestClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l contestClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l contestClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l mediumClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l mediumClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l mediumClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l minimaxClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l minimaxClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l minimaxClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l openClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l openClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l openClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l originalClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l originalClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l originalClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l powerClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l powerClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l powerClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l smallClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l smallClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l smallClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l testClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l testClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l testClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l trappedClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l trappedClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l trappedClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l trickyClassic -p MinimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l trickyClassic -p AlphaBetaAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l trickyClassic -p ExpectimaxAgent -a depth=2,evalFn=scoreEvaluationFunction  --timeout 1 
python pacman.py -l capsuleClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l capsuleClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l capsuleClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l contestClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l contestClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l contestClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l mediumClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l mediumClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l mediumClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l minimaxClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l minimaxClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l minimaxClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l openClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l openClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l openClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l originalClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l originalClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l originalClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l powerClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l powerClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l powerClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l smallClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l smallClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l smallClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l testClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l testClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l testClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l trappedClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l trappedClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l trappedClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l trickyClassic -p MinimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l trickyClassic -p AlphaBetaAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
python pacman.py -l trickyClassic -p ExpectimaxAgent -a depth=2,evalFn=betterEvaluationFunction  --timeout 1 
